name: K6 Load Test

on: [push]

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run K6 Load Test
      uses: grafana/k6-action@v0.2.0
      with:
        filename: scripts\/test.js

    - run: ls & mkdir report & mv index.html report

    - name: Upload artefato
      uses: actions/upload-artifact@v3
      with: 
        name: relatório de teste de performance
        path: report
